apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-stacklayer
  namespace: hello-stacklayer
spec:
  selector:
    matchLabels:
      app: hello-stacklayer
  endpoints:
    - port: http
      path: /metrics
      interval: 30s